#!/usr/bin/env sh

# general
yabai -m config layout bsp
yabai -m config split_ratio 0.50
yabai -m config split_type auto
yabai -m config window_placement second_child
yabai -m config auto_balance off

# padding
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

# mouse
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

# exceptions
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Finder$" title="^(Copy|Move|Info|Get Info)$" manage=off
yabai -m rule --add app="^(Calculator|App Store)$" manage=off
