unbind -T prefix C-Up
unbind -T prefix C-Down
unbind -T prefix C-Left
unbind -T prefix C-Right

bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5
